#!/usr/bin/python3
import yaml
import argparse
import os
import pwd
import json
import sys
import subprocess
import shutil
import sheetutils
import logging
import openpyxl
import csv

def get_username():
    return pwd.getpwuid(os.getuid())[0]

def setup_logger(name, log_file, level=logging.DEBUG):
    """To setup as many loggers as needed"""
    handler = logging.FileHandler(log_file)
    handler.setFormatter(log_formatter)
    logger = logging.getLogger(name)
    logger.setLevel(level)
    logger.addHandler(handler)
    return logger

def read_yaml_file(path):
    with open(path, "r") as stream:
        return yaml.FullLoader(stream).get_data()

def str_to_bool(value):
    if value.lower() in {'true','t','yes','y','1'}:
        return True
    elif value.lower() in {'false','f','no','n','0'}:
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected')

parser = argparse.ArgumentParser(description='Run..')
parser.add_argument('--config-file', dest="config_file", required=True, help='Config file.')
parser.add_argument('--xls-file', dest="xls_file", required=False, help='XLS file.')
parser.add_argument('--batch-name', dest="batch_name", required=True, help='Name of the batch.')
parser.add_argument('--use-google', dest='use_google', type=str_to_bool, required=False, default=False, help='Use Google Sheet.')
parser.add_argument('--google-sheet-id', dest='google_sheet_id', required=False)
parser.add_argument('--google-sheet-name', dest='google_sheet_name', default="Sheet1", required=False)
parser.add_argument('--google-creds-file', dest='google_sheet_creds', required=False)
args = parser.parse_args()

# Set configuration variables from config-file parameter
username            = get_username()
cfg                 = read_yaml_file(args.config_file)
workbench_path      = cfg['workbench_path']
scanning_path       = cfg['scanning_path']
python_exe          = cfg['python_exe']

if ( args.batch_name ):
    batch_name = args.batch_name
else:
    batch_name = os.path.splitext(os.path.basename(args.xls_file))[0]


def create_batch_folder(scanning_path, batch_name):
    batch_path = scanning_path+"/"+batch_name

    print(f"Creating Batch Path: {batch_path}")
    if ( os.path.isdir(batch_path) ):
        print(f"Error: {batch_path} exists!")
        exit()
    else:
        os.mkdir(batch_path)
    return batch_path

def copy_xslx_to_batch(batch_path):
    if os.path.isfile(batch_path+"/manifest.xlsx"):
        print(f"Copying spreadsheet to {batch_path}/manifest.xlsx")
        shutil.copyfile(args.xls_file, batch_path+"/manifest.xlsx")
    else:
        print(f"Error: {batch_path}/manifest.xlsx does not exist.")
        exit()

def save_xslx_as_csv():
    print(f"Creating spreadsheet as csv")
    wb = openpyxl.load_workbook(args.xls_file)
    sheetnames = wb.sheetnames
    sheet_value_arr = []
    for a in sheetnames:
        sheet = wb[a]
        with open(batch_path+"/manifest.csv", "w") as f:
            c = csv.writer(f)
            for row in sheet.rows:
                sheet_value_arr.append([cell.value for cell in row])
                #for r in sheet.rows:
                c.writerow([cell.value for cell in row])

def xls_file_as_df(xls_file):
    print(f"Reading spreadsheet: {xls_file}")
    workbook = openpyxl.load_workbook(xls_file)
    dataframe = workbook.active

def make_dirs_from_df(dataframe):
    rows = dataframe.iterrows()
    for _, row in rows:
        #print(row)
        #if ((str(row.iloc[0])) and (str(row.iloc[0]) != "None" )): 
        if (str(row.loc['id']) and (str(row.loc['id']) != "None" )): 
            id = str(row.loc['id'])
            print(f"Creating {batch_path}/{id}")
            object_path = batch_path + "/" + id
            try: 
                os.mkdir(object_path)
            except OSError as error:
                print(f"Warning: {batch_path}/{id} - {error}.")


if __name__ == '__main__':
    if args.use_google:
        if not args.google_sheet_creds:
            print(f"Error: --google-sheet-creds is required.")
        if not args.google_sheet_id:
            print(f"Error: --google-sheet-id is required.")
        if not args.google_sheet_name:
            print(f"Error: --google-sheet-name is required.")
        if args.google_sheet_creds and args.google_sheet_id and args.google_sheet_name and os.path.isfile(args.google_sheet_creds): 
            manager = sheetutils.GoogleSheetManager()
            manager.connect(args.google_sheet_creds)
            sheet = manager.sheet(args.google_sheet_id, args.google_sheet_name)
            df = sheet.read()
            batch_path = create_batch_folder(scanning_path, batch_name)
            # Make sure the df has an 'id' column and data rows
            if ('id' in df.columns):
                # Make sure the df has rows besides the header row.
                if (len(df) > 0):
                    make_dirs_from_df(df)
                else:
                    print(f"Error: Sheet contains no data.")
            else:
                print(f"Error: Column 'id' does not exist.")
                exit()
        else:
            print(f"Error: Google arguments are required when using Google Sheets.")
            exit()
    else:
        print(f"Creating Batch folder: {scanning_path}/{batch_name}")
        batch_path = create_batch_folder(scanning_path, batch_name)
        copy_xslx_to_batch(batch_path)
        save_xslx_as_csv()
        df = xls_file_as_df(args.xls_file)
        make_dirs_from_df(df)
    
    print(f"Batch Path Creation Complete.")

